[package]
name = "portfolio-api"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.38"
envconfig = "0.10.0"
serde = { version = "1.0.197", features = ["derive"] }
actix-web = "4.5.1"
serde_json = "1.0.116"
tracing = { version = "0.1.40" }
tracing-loki = "0.2.4"
tracing-subscriber = { version = "0.3.18", features = ["json"] }
tokio = "1.37.0"
diesel =  { version = "2.2.11", features = [ "postgres", "r2d2", "chrono"] }
config = { version = "0.15.13", features = ["toml"] }
url = "2.5.4"
openidconnect = { version = "3", default-features = false, features = ["reqwest", "rustls-tls"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
jsonwebtoken = "9"
once_cell = "1.21.3"
rand = { version = "0.8.5", features = ["std"] }
base64 = "0.22.1"
actix-files = "0.6.6"
anyhow = "1.0.98"
actix-cors = "0.7.1"
aws-config = { version = "1.8.12", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = { version = "1.101.0", features = ["behavior-version-latest"] }
serde_dynamo = { version = "4.3.0", features = ["aws-sdk-dynamodb+1"] }