[package]
name = "portfolio-api"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.38"
envconfig = "0.10.0"
serde = { version = "1.0.197", features = ["derive"] }
actix-web = "4.5.1"
serde_json = "1.0.116"
tracing = { version = "0.1.40" }
tracing-loki = "0.2.4"
tracing-subscriber = { version = "0.3.18", features = ["json"] }
tokio = "1.37.0"
config = { version = "0.15.13", features = ["toml"] }
url = "2.5.4"
once_cell = "1.21.3"
actix-files = "0.6.6"
anyhow = "1.0.98"
actix-cors = "0.7.1"
aws-config = { version = "1.8.12", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = { version = "1.101.0", features = ["behavior-version-latest"] }
serde_dynamo = { version = "4.3.0", features = ["aws-sdk-dynamodb+1"] }